spring:
  profiles:
    active: service

# common
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data

# local
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
  profiles: local
  port: 8080

# on service
---
spring:
  profiles: service
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_data
    username: root
    # admin
    password: root
    # vpmember1!
    mapper-locations:classpath:/mapper/**/*.xml
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15

server:
  profiles: service
  port: 8081